---
- name: Upload cdi
  hosts: localhost
  tasks:
  - name: Upload local image to win2012-iso-cephfs-vol1
    kubevirt_cdi_upload:
      pvc_namespace: openshift-cnv
      pvc_name: win2012-iso-cephfs-vol1
      upload_host: https://cdi-uploadproxy-openshift-cnv.apps.cluster-dubai-42bb.dubai-42bb.example.opentlc.com
      upload_host_validate_certs: false
      path: ./isos/es_wiDws_server_2012_r2_x64_dvd_2708013.iso