---
- name: Upload cdi
  hosts: localhost
  tasks:
  - name: Upload local image to centos8-iso-cephfs-vol1
    kubevirt_cdi_upload:
      pvc_namespace: openshift-cnv
      pvc_name: centos8-iso-cephfs-vol1
      upload_host: https://cdi-uploadproxy-openshift-cnv.apps.cluster-dubai-42bb.dubai-42bb.example.opentlc.com
      upload_host_validate_certs: false
      path: ./isos/CentOS-8.1.1911-x86_64-dvd1.iso