apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  namespace: openshift-cnv
  name: win2012-iso-cephfs-vol1
spec:
  source:
      upload: {}
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: ocs-storagecluster-cephfs