---
- name: Prepare machinesets for OCS, from existing workers machinesets
  hosts: localhost
  connection: local
  vars_files:
      - ./vars/vars.yml
  tasks:
    - name: Collect the machinesets names
      shell:
                cmd: |
                  oc -n {{ machineset_project }} get machinesets -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'
      register: machinesets
    - name: Export the machinesets in yaml files
      shell:
                cmd: |
                        oc -n {{ machineset_project }} get machinesets {{ item }} -o yaml |  sed -e 's/{{ item }}/ocs-worker-{{ item.split('-')[4:7] | join('-') }}/g' > ocs-worker-{{ item.split('-')[4:7] | join('-') }}.yaml
      loop: "{{ machinesets.stdout_lines }}"